Feature auth v1
sapient-jun-2022/team3-goTour-auth pull request #1
Opened 2022-06-27 10:09 UTC by sailesh97

@adithnaveen @IrshadMulani @ayushk96

2022-06-27 10:21 UTC, adithnaveen requested changes
pls look a the comments

2022-06-27 10:21 UTC, adithnaveen commented on src/controllers/auth-controller.js
> +                error: err._message,
```suggestion
                error: err.code,
```

2022-06-27 10:21 UTC, adithnaveen commented on src/models/customer-model.js
>          phone: {
```suggestion
        phone: Number
```

would be better as there is on validation

2022-06-27 10:21 UTC, adithnaveen commented on src/models/customer-model.js
>              type: String
@sailesh97  pls refer to earlier comment

2022-06-27 10:35 UTC, sailesh97 commented on src/controllers/auth-controller.js
> +                error: err._message,
This is the code for error handling for duplicate users with same email/aadhar no/ username. The error object I'm getting is like below:
`
{
  "errors": {
    "customerName": {
    },
    "email": {
    },
    "aadharNo": {
    }
  },
  "_message": "user validation failed",
  "name": "ValidationError",
  "message": "user validation failed: customerName: Error, expected `customerName` to be unique. Value: `Sailesh Patra`, email: Error, expected `email` to be unique. Value: `sailes@gmail.com`, aadharNo: Error, expected `aadharNo` to be unique. Value: `4553-9009-4621`"
}
`

There's no "code" key in the error object.
@adithnaveen

2022-06-27 10:36 UTC, sailesh97 commented on src/models/customer-model.js
>          phone: {
I'll do the neccessary changes here

2022-06-29 10:33 UTC, adithnaveen approved these changes
merging to master

2022-06-29 10:34 UTC, merged